// import doctor from "../assets/img/profiles/avatar-12.jpg";
import doctor from "../assets/img/doctors/rectangle-103@2x.png";

const doctors = [
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Laywers ",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Security",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Pharmacist",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
  {
    doctor_title: "Doctors",
    doctor_images: [doctor, doctor],
    total_consultants: "3,000,000",
    total_consultants_online: "1,000,000",
    average_exprience: "5yrs",
    total_consultations: "15Million+",
  },
];

export default doctors;
